<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-07-09 06:49
=======
# Generated by Django 4.2.3 on 2023-08-28 00:33
>>>>>>> package_request

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
=======
import phonenumber_field.modelfields
>>>>>>> package_request
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
<<<<<<< HEAD
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
=======
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
>>>>>>> package_request
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
<<<<<<< HEAD
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profile_images/user-default.png', null=True, upload_to='profile_images/')),
=======
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/')),
>>>>>>> package_request
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
