# Generated by Django 4.2.3 on 2023-07-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='customer_id',
        ),
    ]
