# Generated by Django 4.2.4 on 2023-08-12 15:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('sender_address', models.CharField(max_length=200)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('recipient_address', models.CharField(max_length=200)),
                ('package_description', models.CharField(max_length=200)),
                ('fragile', models.BooleanField()),
                ('estimate_package_weight', models.CharField(choices=[('<2', '<2'), ('2-5', '2-5'), ('5-10', '5-10'), ('>10', '>10')], max_length=5)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('sender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
    ]
