# Generated by Django 4.2.3 on 2024-02-24 15:40

from django.db import migrations, models
import phonenumber_field.modelfields
import places.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('sender_address', places.fields.PlacesField(blank=True, max_length=255)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TW')),
                ('recipient_address', places.fields.PlacesField(blank=True, max_length=255)),
                ('package_description', models.CharField(max_length=200)),
                ('fragile', models.BooleanField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picking', 'Picking'), ('delivering', 'Delivering'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('estimate_package_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcels', models.ManyToManyField(blank=True, related_name='route', to='package_request.package')),
            ],
        ),
    ]
