# Generated by Django 4.2.3 on 2024-02-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_request', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='estimate_package_weight_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='estimate_package_weight',
            field=models.CharField(choices=[('<2', '<2'), ('2-5', '2-5'), ('5-10', '5-10'), ('>10', '>10')], default='<2', max_length=5),
        ),
    ]
