# Generated by Django 4.2.3 on 2024-02-24 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('package_request', '0005_alter_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
