# Generated by Django 4.2.3 on 2024-04-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package_request', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='parcel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='package_request.package'),
        ),
    ]
